[project]
name = "tz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=3.22.0",
    "aiohttp>=3.12.15",
    "aiomysql>=0.2.0",
    "dotenv>=0.9.9",
    "matplotlib>=3.10.6",
]
